//create
export const  DELIVERY_NOTE_CREATE_REQUEST = 'DELIVERY_NOTE_CREATE_REQUEST'
export const  DELIVERY_NOTE_CREATE_SUCCESS = 'DELIVERY_NOTE_CREATE_SUCCESS'
export const  DELIVERY_NOTE_CREATE_FAIL = 'DELIVERY_NOTE_CREATE_FAIL'
export const  DELIVERY_NOTE_CREATE_RESET = 'DELIVERY_NOTE_CREATE_RESET'

//read
export const DELIVERY_NOTE_DETAILS_REQUEST = 'DELIVERY_NOTE_DETAILS_REQUEST'
export const DELIVERY_NOTE_DETAILS_SUCCESS = 'DELIVERY_NOTE_DETAILS_SUCCESS'
export const DELIVERY_NOTE_DETAILS_FAIL = 'DELIVERY_NOTE_DETAILS_FAIL'
export const DELIVERY_NOTE_DETAILS_RESET = 'DELIVERY_NOTE_DETAILS_RESET'

//update
export const DELIVERY_NOTE_UPDATE_REQUEST = 'DELIVERY_NOTE_UPDATE_REQUEST'
export const DELIVERY_NOTE_UPDATE_SUCCESS = 'DELIVERY_NOTE_UPDATE_SUCCESS'
export const DELIVERY_NOTE_UPDATE_FAIL = 'DELIVERY_NOTE_UPDATE_FAIL'
export const DELIVERY_NOTE_UPDATE_RESET = 'DELIVERY_NOTE_UPDATE_RESET'

//delete
export const DELIVERY_NOTE_DELETE_REQUEST = 'DELIVERY_NOTE_DELETE_REQUEST'
export const DELIVERY_NOTE_DELETE_SUCCESS = 'DELIVERY_NOTE_DELETE_SUCCESS'
export const DELIVERY_NOTE_DELETE_FAIL = 'DELIVERY_NOTE_DELETE_FAIL'
export const DELIVERY_NOTE_DELETE_RESET = 'DELIVERY_NOTE_DELETE_RESET'

//all records
export const DELIVERY_NOTE_LIST_REQUEST = 'DELIVERY_NOTE_LIST_REQUEST'
export const DELIVERY_NOTE_LIST_SUCCESS = 'DELIVERY_NOTE_LIST_SUCCESS'
export const DELIVERY_NOTE_LIST_FAIL = 'DELIVERY_NOTE_LIST_FAIL'
export const DELIVERY_NOTE_LIST_RESET = 'DELIVERY_NOTE_LIST_RESET'

//all master data for Delivery Note
export const DELIVERY_NOTE_MASTER_LIST_REQUEST = 'DELIVERY_NOTE_MASTER_LIST_REQUEST'
export const DELIVERY_NOTE_MASTER_LIST_SUCCESS = 'DELIVERY_NOTE_MASTER_LIST_SUCCESS'
export const DELIVERY_NOTE_MASTER_LIST_FAIL = 'DELIVERY_NOTE_MASTER_LIST_FAIL'
export const DELIVERY_NOTE_MASTER_LIST_RESET = 'DELIVERY_NOTE_MASTER_LIST_RESET'