//create
export const  DISPATCH_DETAILS_CREATE_REQUEST = 'DISPATCH_DETAILS_CREATE_REQUEST'
export const  DISPATCH_DETAILS_CREATE_SUCCESS = 'DISPATCH_DETAILS_CREATE_SUCCESS'
export const  DISPATCH_DETAILS_CREATE_FAIL = 'DISPATCH_DETAILS_CREATE_FAIL'
export const  DISPATCH_DETAILS_CREATE_RESET = 'DISPATCH_DETAILS_CREATE_RESET'

//read
export const DISPATCH_DETAILS_DETAILS_REQUEST = 'DISPATCH_DETAILS_DETAILS_REQUEST'
export const DISPATCH_DETAILS_DETAILS_SUCCESS = 'DISPATCH_DETAILS_DETAILS_SUCCESS'
export const DISPATCH_DETAILS_DETAILS_FAIL = 'DISPATCH_DETAILS_DETAILS_FAIL'
export const DISPATCH_DETAILS_DETAILS_RESET = 'DISPATCH_DETAILS_DETAILS_RESET'

//update
export const DISPATCH_DETAILS_UPDATE_REQUEST = 'DISPATCH_DETAILS_UPDATE_REQUEST'
export const DISPATCH_DETAILS_UPDATE_SUCCESS = 'DISPATCH_DETAILS_UPDATE_SUCCESS'
export const DISPATCH_DETAILS_UPDATE_FAIL = 'DISPATCH_DETAILS_UPDATE_FAIL'
export const DISPATCH_DETAILS_UPDATE_RESET = 'DISPATCH_DETAILS_UPDATE_RESET'

//delete
export const DISPATCH_DETAILS_DELETE_REQUEST = 'DISPATCH_DETAILS_DELETE_REQUEST'
export const DISPATCH_DETAILS_DELETE_SUCCESS = 'DISPATCH_DETAILS_DELETE_SUCCESS'
export const DISPATCH_DETAILS_DELETE_FAIL = 'DISPATCH_DETAILS_DELETE_FAIL'
export const DISPATCH_DETAILS_DELETE_RESET = 'DISPATCH_DETAILS_DELETE_RESET'

//all records
export const DISPATCH_DETAILS_LIST_REQUEST = 'DISPATCH_DETAILS_LIST_REQUEST'
export const DISPATCH_DETAILS_LIST_SUCCESS = 'DISPATCH_DETAILS_LIST_SUCCESS'
export const DISPATCH_DETAILS_LIST_FAIL = 'DISPATCH_DETAILS_LIST_FAIL'
export const DISPATCH_DETAILS_LIST_RESET = 'DISPATCH_DETAILS_LIST_RESET'

//all master data for Dispatch Details
export const DISPATCH_DETAILS_MASTER_LIST_REQUEST = 'DISPATCH_DETAILS_MASTER_LIST_REQUEST'
export const DISPATCH_DETAILS_MASTER_LIST_SUCCESS = 'DISPATCH_DETAILS_MASTER_LIST_SUCCESS'
export const DISPATCH_DETAILS_MASTER_LIST_FAIL = 'DISPATCH_DETAILS_MASTER_LIST_FAIL'
export const DISPATCH_DETAILS_MASTER_LIST_RESET = 'DISPATCH_DETAILS_MASTER_LIST_RESET'