//create
export const  DRN_CREATE_REQUEST = ' DRN_CREATE_REQUEST'
export const  DRN_CREATE_SUCCESS = ' DRN_CREATE_SUCCESS'
export const  DRN_CREATE_FAIL = ' DRN_CREATE_FAIL'
export const  DRN_CREATE_RESET = ' DRN_CREATE_RESET'

//read
export const DRN_DETAILS_REQUEST = 'DRN_DETAILS_REQUEST'
export const DRN_DETAILS_SUCCESS = 'DRN_DETAILS_SUCCESS'
export const DRN_DETAILS_FAIL = 'DRN_DETAILS_FAIL'
export const DRN_DETAILS_RESET = 'DRN_DETAILS_RESET'

//update
export const DRN_UPDATE_REQUEST = 'DRN_UPDATE_REQUEST'
export const DRN_UPDATE_SUCCESS = 'DRN_UPDATE_SUCCESS'
export const DRN_UPDATE_FAIL = 'DRN_UPDATE_FAIL'
export const DRN_UPDATE_RESET = 'DRN_UPDATE_RESET'

//delete
export const DRN_DELETE_REQUEST = 'DRN_DELETE_REQUEST'
export const DRN_DELETE_SUCCESS = 'DRN_DELETE_SUCCESS'
export const DRN_DELETE_FAIL = 'DRN_DELETE_FAIL'
export const DRN_DELETE_RESET = 'DRN_DELETE_RESET'

//all records
export const DRN_LIST_REQUEST = 'DRN_LIST_REQUEST'
export const DRN_LIST_SUCCESS = 'DRN_LIST_SUCCESS'
export const DRN_LIST_FAIL = 'DRN_LIST_FAIL'
export const DRN_LIST_RESET = 'DRN_LIST_RESET'

//all master data for JC Master
export const DRN_MASTER_LIST_REQUEST = 'DRN_MASTER_LIST_REQUEST'
export const DRN_MASTER_LIST_SUCCESS = 'DRN_MASTER_LIST_SUCCESS'
export const DRN_MASTER_LIST_FAIL = 'DRN_MASTER_LIST_FAIL'
export const DRN_MASTER_LIST_RESET = 'DRN_MASTER_LIST_RESET'

//all open DRN records
export const DRN_OPEN_LIST_REQUEST = 'DRN_OPEN_LIST_REQUEST'
export const DRN_OPEN_LIST_SUCCESS = 'DRN_OPEN_LIST_SUCCESS'
export const DRN_OPEN_LIST_FAIL = 'DRN_OPEN_LIST_FAIL'
export const DRN_OPEN_LIST_RESET = 'DRN_OPEN_LIST_RESET'

//all Approved DRN records
export const DRN_APPROVED_LIST_REQUEST = 'DRN_APPROVED_LIST_REQUEST'
export const DRN_APPROVED_LIST_SUCCESS = 'DRN_APPROVED_LIST_SUCCESS'
export const DRN_APPROVED_LIST_FAIL = 'DRN_APPROVED_LIST_FAIL'
export const DRN_APPROVED_LIST_RESET = 'DRN_APPROVED_LIST_RESET'

//all Rejected DRN records
export const DRN_REJECTED_LIST_REQUEST = 'DRN_REJECTED_LIST_REQUEST'
export const DRN_REJECTED_LIST_SUCCESS = 'DRN_REJECTED_LIST_SUCCESS'
export const DRN_REJECTED_LIST_FAIL = 'DRN_REJECTED_LIST_FAIL'
export const DRN_REJECTED_LIST_RESET = 'DRN_REJECTED_LIST_RESET'