//create
export const  FGMI_CREATE_REQUEST = ' FGMI_CREATE_REQUEST'
export const  FGMI_CREATE_SUCCESS = ' FGMI_CREATE_SUCCESS'
export const  FGMI_CREATE_FAIL = ' FGMI_CREATE_FAIL'
export const  FGMI_CREATE_RESET = ' FGMI_CREATE_RESET'

//read
export const FGMI_DETAILS_REQUEST = 'FGMI_DETAILS_REQUEST'
export const FGMI_DETAILS_SUCCESS = 'FGMI_DETAILS_SUCCESS'
export const FGMI_DETAILS_FAIL = 'FGMI_DETAILS_FAIL'
export const FGMI_DETAILS_RESET = 'FGMI_DETAILS_RESET'

//update
export const FGMI_UPDATE_REQUEST = 'FGMI_UPDATE_REQUEST'
export const FGMI_UPDATE_SUCCESS = 'FGMI_UPDATE_SUCCESS'
export const FGMI_UPDATE_FAIL = 'FGMI_UPDATE_FAIL'
export const FGMI_UPDATE_RESET = 'FGMI_UPDATE_RESET'

//delete
export const FGMI_DELETE_REQUEST = 'FGMI_DELETE_REQUEST'
export const FGMI_DELETE_SUCCESS = 'FGMI_DELETE_SUCCESS'
export const FGMI_DELETE_FAIL = 'FGMI_DELETE_FAIL'
export const FGMI_DELETE_RESET = 'FGMI_DELETE_RESET'

//all records
export const FGMI_LIST_REQUEST = 'FGMI_LIST_REQUEST'
export const FGMI_LIST_SUCCESS = 'FGMI_LIST_SUCCESS'
export const FGMI_LIST_FAIL = 'FGMI_LIST_FAIL'
export const FGMI_LIST_RESET = 'FGMI_LIST_RESET'

//all master data for Job Card Screen
export const FGMI_MASTER_LIST_REQUEST = 'FGMI_MASTER_LIST_REQUEST'
export const FGMI_MASTER_LIST_SUCCESS = 'FGMI_MASTER_LIST_SUCCESS'
export const FGMI_MASTER_LIST_FAIL = 'FGMI_MASTER_LIST_FAIL'
export const FGMI_MASTER_LIST_RESET = 'FGMI_MASTER_LIST_RESET'

//all FGMI bacthes by JC ID
export const FGMI_BACTH_LIST_BY_JC_REQUEST = 'FGMI_BACTH_LIST_BY_JC_REQUEST'
export const FGMI_BACTH_LIST_BY_JC_SUCCESS = 'FGMI_BACTH_LIST_BY_JC_SUCCESS'
export const FGMI_BACTH_LIST_BY_JC_FAIL = 'FGMI_BACTH_LIST_BY_JC_FAIL'
export const FGMI_BACTH_LIST_BY_JC_RESET = 'FGMI_BACTH_LIST_BY_JC_RESET'

//update fgmi thru correction
export const FGMI_CORRECTION_UPDATE_REQUEST = 'FGMI_CORRECTION_UPDATE_REQUEST'
export const FGMI_CORRECTION_UPDATE_SUCCESS = 'FGMI_CORRECTION_UPDATE_SUCCESS'
export const FGMI_CORRECTION_UPDATE_FAIL = 'FGMI_CORRECTION_UPDATE_FAIL'
export const FGMI_CORRECTION_UPDATE_RESET = 'FGMI_CORRECTION_UPDATE_RESET'