//create
export const  JOB_CARD_CREATE_REQUEST = ' JOB_CARD_CREATE_REQUEST'
export const  JOB_CARD_CREATE_SUCCESS = ' JOB_CARD_CREATE_SUCCESS'
export const  JOB_CARD_CREATE_FAIL = ' JOB_CARD_CREATE_FAIL'
export const  JOB_CARD_CREATE_RESET = ' JOB_CARD_CREATE_RESET'

//read
export const JOB_CARD_DETAILS_REQUEST = 'JOB_CARD_DETAILS_REQUEST'
export const JOB_CARD_DETAILS_SUCCESS = 'JOB_CARD_DETAILS_SUCCESS'
export const JOB_CARD_DETAILS_FAIL = 'JOB_CARD_DETAILS_FAIL'
export const JOB_CARD_DETAILS_RESET = 'JOB_CARD_DETAILS_RESET'

//update
export const JOB_CARD_UPDATE_REQUEST = 'JOB_CARD_UPDATE_REQUEST'
export const JOB_CARD_UPDATE_SUCCESS = 'JOB_CARD_UPDATE_SUCCESS'
export const JOB_CARD_UPDATE_FAIL = 'JOB_CARD_UPDATE_FAIL'
export const JOB_CARD_UPDATE_RESET = 'JOB_CARD_UPDATE_RESET'

//delete
export const JOB_CARD_DELETE_REQUEST = 'JOB_CARD_DELETE_REQUEST'
export const JOB_CARD_DELETE_SUCCESS = 'JOB_CARD_DELETE_SUCCESS'
export const JOB_CARD_DELETE_FAIL = 'JOB_CARD_DELETE_FAIL'
export const JOB_CARD_DELETE_RESET = 'JOB_CARD_DELETE_RESET'

//all records
export const JOB_CARD_LIST_REQUEST = 'JOB_CARD_LIST_REQUEST'
export const JOB_CARD_LIST_SUCCESS = 'JOB_CARD_LIST_SUCCESS'
export const JOB_CARD_LIST_FAIL = 'JOB_CARD_LIST_FAIL'
export const JOB_CARD_LIST_RESET = 'JOB_CARD_LIST_RESET'

//all master data for Job Card Screen
export const JOB_CARD_MASTER_LIST_REQUEST = 'JOB_CARD_MASTER_LIST_REQUEST'
export const JOB_CARD_MASTER_LIST_SUCCESS = 'JOB_CARD_MASTER_LIST_SUCCESS'
export const JOB_CARD_MASTER_LIST_FAIL = 'JOB_CARD_MASTER_LIST_FAIL'
export const JOB_CARD_MASTER_LIST_RESET = 'JOB_CARD_MASTER_LIST_RESET'

//yield report
export const YIELD_REPORT_REQUEST = 'YIELD_REPORT_REQUEST'
export const YIELD_REPORT_SUCCESS = 'YIELD_REPORT_SUCCESS'
export const YIELD_REPORT_FAIL = 'YIELD_REPORT_FAIL'
export const YIELD_REPORT_RESET = 'YIELD_REPORT_RESET'