//create
export const  INSPECTION_PARAM_CREATE_REQUEST = 'INSPECTION_PARAM_CREATE_REQUEST'
export const  INSPECTION_PARAM_CREATE_SUCCESS = 'INSPECTION_PARAM_CREATE_SUCCESS'
export const  INSPECTION_PARAM_CREATE_FAIL = 'INSPECTION_PARAM_CREATE_FAIL'
export const  INSPECTION_PARAM_CREATE_RESET = 'INSPECTION_PARAM_CREATE_RESET'

//read
export const INSPECTION_PARAM_DETAILS_REQUEST = 'INSPECTION_PARAM_DETAILS_REQUEST'
export const INSPECTION_PARAM_DETAILS_SUCCESS = 'INSPECTION_PARAM_DETAILS_SUCCESS'
export const INSPECTION_PARAM_DETAILS_FAIL = 'INSPECTION_PARAM_DETAILS_FAIL'
export const INSPECTION_PARAM_DETAILS_RESET = 'INSPECTION_PARAM_DETAILS_RESET'

//update
export const INSPECTION_PARAM_UPDATE_REQUEST = 'INSPECTION_PARAM_UPDATE_REQUEST'
export const INSPECTION_PARAM_UPDATE_SUCCESS = 'INSPECTION_PARAM_UPDATE_SUCCESS'
export const INSPECTION_PARAM_UPDATE_FAIL = 'INSPECTION_PARAM_UPDATE_FAIL'
export const INSPECTION_PARAM_UPDATE_RESET = 'INSPECTION_PARAM_UPDATE_RESET'

//delete
export const INSPECTION_PARAM_DELETE_REQUEST = 'INSPECTION_PARAM_DELETE_REQUEST'
export const INSPECTION_PARAM_DELETE_SUCCESS = 'INSPECTION_PARAM_DELETE_SUCCESS'
export const INSPECTION_PARAM_DELETE_FAIL = 'INSPECTION_PARAM_DELETE_FAIL'
export const INSPECTION_PARAM_DELETE_RESET = 'INSPECTION_PARAM_DELETE_RESET'

//all records
export const INSPECTION_PARAM_LIST_REQUEST = 'INSPECTION_PARAM_LIST_REQUEST'
export const INSPECTION_PARAM_LIST_SUCCESS = 'INSPECTION_PARAM_LIST_SUCCESS'
export const INSPECTION_PARAM_LIST_FAIL = 'INSPECTION_PARAM_LIST_FAIL'
export const INSPECTION_PARAM_LIST_RESET = 'INSPECTION_PARAM_LIST_RESET'

//all master data for Module
export const INSPECTION_PARAM_MASTER_LIST_REQUEST = 'INSPECTION_PARAM_MASTER_LIST_REQUEST'
export const INSPECTION_PARAM_MASTER_LIST_SUCCESS = 'INSPECTION_PARAM_MASTER_LIST_SUCCESS'
export const INSPECTION_PARAM_MASTER_LIST_FAIL = 'INSPECTION_PARAM_MASTER_LIST_FAIL'
export const INSPECTION_PARAM_MASTER_LIST_RESET = 'INSPECTION_PARAM_MASTER_LIST_RESET'