//create
export const  INSPECTION_METHOD_CREATE_REQUEST = 'INSPECTION_METHOD_CREATE_REQUEST'
export const  INSPECTION_METHOD_CREATE_SUCCESS = 'INSPECTION_METHOD_CREATE_SUCCESS'
export const  INSPECTION_METHOD_CREATE_FAIL = 'INSPECTION_METHOD_CREATE_FAIL'
export const  INSPECTION_METHOD_CREATE_RESET = 'INSPECTION_METHOD_CREATE_RESET'

//read
export const INSPECTION_METHOD_DETAILS_REQUEST = 'INSPECTION_METHOD_DETAILS_REQUEST'
export const INSPECTION_METHOD_DETAILS_SUCCESS = 'INSPECTION_METHOD_DETAILS_SUCCESS'
export const INSPECTION_METHOD_DETAILS_FAIL = 'INSPECTION_METHOD_DETAILS_FAIL'
export const INSPECTION_METHOD_DETAILS_RESET = 'INSPECTION_METHOD_DETAILS_RESET'

//update
export const INSPECTION_METHOD_UPDATE_REQUEST = 'INSPECTION_METHOD_UPDATE_REQUEST'
export const INSPECTION_METHOD_UPDATE_SUCCESS = 'INSPECTION_METHOD_UPDATE_SUCCESS'
export const INSPECTION_METHOD_UPDATE_FAIL = 'INSPECTION_METHOD_UPDATE_FAIL'
export const INSPECTION_METHOD_UPDATE_RESET = 'INSPECTION_METHOD_UPDATE_RESET'

//delete
export const INSPECTION_METHOD_DELETE_REQUEST = 'INSPECTION_METHOD_DELETE_REQUEST'
export const INSPECTION_METHOD_DELETE_SUCCESS = 'INSPECTION_METHOD_DELETE_SUCCESS'
export const INSPECTION_METHOD_DELETE_FAIL = 'INSPECTION_METHOD_DELETE_FAIL'
export const INSPECTION_METHOD_DELETE_RESET = 'INSPECTION_METHOD_DELETE_RESET'

//all records
export const INSPECTION_METHOD_LIST_REQUEST = 'INSPECTION_METHOD_LIST_REQUEST'
export const INSPECTION_METHOD_LIST_SUCCESS = 'INSPECTION_METHOD_LIST_SUCCESS'
export const INSPECTION_METHOD_LIST_FAIL = 'INSPECTION_METHOD_LIST_FAIL'
export const INSPECTION_METHOD_LIST_RESET = 'INSPECTION_METHOD_LIST_RESET'

//all master data for Module
export const INSPECTION_METHOD_MASTER_LIST_REQUEST = 'INSPECTION_METHOD_MASTER_LIST_REQUEST'
export const INSPECTION_METHOD_MASTER_LIST_SUCCESS = 'INSPECTION_METHOD_MASTER_LIST_SUCCESS'
export const INSPECTION_METHOD_MASTER_LIST_FAIL = 'INSPECTION_METHOD_MASTER_LIST_FAIL'
export const INSPECTION_METHOD_MASTER_LIST_RESET = 'INSPECTION_METHOD_MASTER_LIST_RESET'