//create
export const  PDIR_CREATE_REQUEST = 'PDIR_CREATE_REQUEST'
export const  PDIR_CREATE_SUCCESS = 'PDIR_CREATE_SUCCESS'
export const  PDIR_CREATE_FAIL = 'PDIR_CREATE_FAIL'
export const  PDIR_CREATE_RESET = 'PDIR_CREATE_RESET'

//read
export const PDIR_DETAILS_REQUEST = 'PDIR_DETAILS_REQUEST'
export const PDIR_DETAILS_SUCCESS = 'PDIR_DETAILS_SUCCESS'
export const PDIR_DETAILS_FAIL = 'PDIR_DETAILS_FAIL'
export const PDIR_DETAILS_RESET = 'PDIR_DETAILS_RESET'

//update
export const PDIR_UPDATE_REQUEST = 'PDIR_UPDATE_REQUEST'
export const PDIR_UPDATE_SUCCESS = 'PDIR_UPDATE_SUCCESS'
export const PDIR_UPDATE_FAIL = 'PDIR_UPDATE_FAIL'
export const PDIR_UPDATE_RESET = 'PDIR_UPDATE_RESET'

//delete
export const PDIR_DELETE_REQUEST = 'PDIR_DELETE_REQUEST'
export const PDIR_DELETE_SUCCESS = 'PDIR_DELETE_SUCCESS'
export const PDIR_DELETE_FAIL = 'PDIR_DELETE_FAIL'
export const PDIR_DELETE_RESET = 'PDIR_DELETE_RESET'

//all records
export const PDIR_LIST_REQUEST = 'PDIR_LIST_REQUEST'
export const PDIR_LIST_SUCCESS = 'PDIR_LIST_SUCCESS'
export const PDIR_LIST_FAIL = 'PDIR_LIST_FAIL'
export const PDIR_LIST_RESET = 'PDIR_LIST_RESET'

//all master data for Module
export const PDIR_MASTER_LIST_REQUEST = 'PDIR_MASTER_LIST_REQUEST'
export const PDIR_MASTER_LIST_SUCCESS = 'PDIR_MASTER_LIST_SUCCESS'
export const PDIR_MASTER_LIST_FAIL = 'PDIR_MASTER_LIST_FAIL'
export const PDIR_MASTER_LIST_RESET = 'PDIR_MASTER_LIST_RESET'