//create
export const  PDIR_TEMPLATE_CREATE_REQUEST = 'PDIR_TEMPLATE_CREATE_REQUEST'
export const  PDIR_TEMPLATE_CREATE_SUCCESS = 'PDIR_TEMPLATE_CREATE_SUCCESS'
export const  PDIR_TEMPLATE_CREATE_FAIL = 'PDIR_TEMPLATE_CREATE_FAIL'
export const  PDIR_TEMPLATE_CREATE_RESET = 'PDIR_TEMPLATE_CREATE_RESET'

//read
export const PDIR_TEMPLATE_DETAILS_REQUEST = 'PDIR_TEMPLATE_DETAILS_REQUEST'
export const PDIR_TEMPLATE_DETAILS_SUCCESS = 'PDIR_TEMPLATE_DETAILS_SUCCESS'
export const PDIR_TEMPLATE_DETAILS_FAIL = 'PDIR_TEMPLATE_DETAILS_FAIL'
export const PDIR_TEMPLATE_DETAILS_RESET = 'PDIR_TEMPLATE_DETAILS_RESET'

//update
export const PDIR_TEMPLATE_UPDATE_REQUEST = 'PDIR_TEMPLATE_UPDATE_REQUEST'
export const PDIR_TEMPLATE_UPDATE_SUCCESS = 'PDIR_TEMPLATE_UPDATE_SUCCESS'
export const PDIR_TEMPLATE_UPDATE_FAIL = 'PDIR_TEMPLATE_UPDATE_FAIL'
export const PDIR_TEMPLATE_UPDATE_RESET = 'PDIR_TEMPLATE_UPDATE_RESET'

//delete
export const PDIR_TEMPLATE_DELETE_REQUEST = 'PDIR_TEMPLATE_DELETE_REQUEST'
export const PDIR_TEMPLATE_DELETE_SUCCESS = 'PDIR_TEMPLATE_DELETE_SUCCESS'
export const PDIR_TEMPLATE_DELETE_FAIL = 'PDIR_TEMPLATE_DELETE_FAIL'
export const PDIR_TEMPLATE_DELETE_RESET = 'PDIR_TEMPLATE_DELETE_RESET'

//all records
export const PDIR_TEMPLATE_LIST_REQUEST = 'PDIR_TEMPLATE_LIST_REQUEST'
export const PDIR_TEMPLATE_LIST_SUCCESS = 'PDIR_TEMPLATE_LIST_SUCCESS'
export const PDIR_TEMPLATE_LIST_FAIL = 'PDIR_TEMPLATE_LIST_FAIL'
export const PDIR_TEMPLATE_LIST_RESET = 'PDIR_TEMPLATE_LIST_RESET'

//all master data for Module
export const PDIR_TEMPLATE_MASTER_LIST_REQUEST = 'PDIR_TEMPLATE_MASTER_LIST_REQUEST'
export const PDIR_TEMPLATE_MASTER_LIST_SUCCESS = 'PDIR_TEMPLATE_MASTER_LIST_SUCCESS'
export const PDIR_TEMPLATE_MASTER_LIST_FAIL = 'PDIR_TEMPLATE_MASTER_LIST_FAIL'
export const PDIR_TEMPLATE_MASTER_LIST_RESET = 'PDIR_TEMPLATE_MASTER_LIST_RESET'