//create
export const  PPM_REPORT_CREATE_REQUEST = 'PPM_REPORT_CREATE_REQUEST'
export const  PPM_REPORT_CREATE_SUCCESS = 'PPM_REPORT_CREATE_SUCCESS'
export const  PPM_REPORT_CREATE_FAIL = 'PPM_REPORT_CREATE_FAIL'
export const  PPM_REPORT_CREATE_RESET = 'PPM_REPORT_CREATE_RESET'

//read
export const PPM_REPORT_DETAILS_REQUEST = 'PPM_REPORT_DETAILS_REQUEST'
export const PPM_REPORT_DETAILS_SUCCESS = 'PPM_REPORT_DETAILS_SUCCESS'
export const PPM_REPORT_DETAILS_FAIL = 'PPM_REPORT_DETAILS_FAIL'
export const PPM_REPORT_DETAILS_RESET = 'PPM_REPORT_DETAILS_RESET'

//update
export const PPM_REPORT_UPDATE_REQUEST = 'PPM_REPORT_UPDATE_REQUEST'
export const PPM_REPORT_UPDATE_SUCCESS = 'PPM_REPORT_UPDATE_SUCCESS'
export const PPM_REPORT_UPDATE_FAIL = 'PPM_REPORT_UPDATE_FAIL'
export const PPM_REPORT_UPDATE_RESET = 'PPM_REPORT_UPDATE_RESET'