//create
export const  CREDIT_NOTE_CREATE_REQUEST = 'CREDIT_NOTE_CREATE_REQUEST'
export const  CREDIT_NOTE_CREATE_SUCCESS = 'CREDIT_NOTE_CREATE_SUCCESS'
export const  CREDIT_NOTE_CREATE_FAIL = 'CREDIT_NOTE_CREATE_FAIL'
export const  CREDIT_NOTE_CREATE_RESET = 'CREDIT_NOTE_CREATE_RESET'

//read
export const CREDIT_NOTE_DETAILS_REQUEST = 'CREDIT_NOTE_DETAILS_REQUEST'
export const CREDIT_NOTE_DETAILS_SUCCESS = 'CREDIT_NOTE_DETAILS_SUCCESS'
export const CREDIT_NOTE_DETAILS_FAIL = 'CREDIT_NOTE_DETAILS_FAIL'
export const CREDIT_NOTE_DETAILS_RESET = 'CREDIT_NOTE_DETAILS_RESET'

//update
export const CREDIT_NOTE_UPDATE_REQUEST = 'CREDIT_NOTE_UPDATE_REQUEST'
export const CREDIT_NOTE_UPDATE_SUCCESS = 'CREDIT_NOTE_UPDATE_SUCCESS'
export const CREDIT_NOTE_UPDATE_FAIL = 'CREDIT_NOTE_UPDATE_FAIL'
export const CREDIT_NOTE_UPDATE_RESET = 'CREDIT_NOTE_UPDATE_RESET'

//delete
export const CREDIT_NOTE_DELETE_REQUEST = 'CREDIT_NOTE_DELETE_REQUEST'
export const CREDIT_NOTE_DELETE_SUCCESS = 'CREDIT_NOTE_DELETE_SUCCESS'
export const CREDIT_NOTE_DELETE_FAIL = 'CREDIT_NOTE_DELETE_FAIL'
export const CREDIT_NOTE_DELETE_RESET = 'CREDIT_NOTE_DELETE_RESET'

//all records
export const CREDIT_NOTE_LIST_REQUEST = 'CREDIT_NOTE_LIST_REQUEST'
export const CREDIT_NOTE_LIST_SUCCESS = 'CREDIT_NOTE_LIST_SUCCESS'
export const CREDIT_NOTE_LIST_FAIL = 'CREDIT_NOTE_LIST_FAIL'
export const CREDIT_NOTE_LIST_RESET = 'CREDIT_NOTE_LIST_RESET'

//all master data for Sales Invoice
export const CREDIT_NOTE_MASTER_LIST_REQUEST = 'CREDIT_NOTE_MASTER_LIST_REQUEST'
export const CREDIT_NOTE_MASTER_LIST_SUCCESS = 'CREDIT_NOTE_MASTER_LIST_SUCCESS'
export const CREDIT_NOTE_MASTER_LIST_FAIL = 'CREDIT_NOTE_MASTER_LIST_FAIL'
export const CREDIT_NOTE_MASTER_LIST_RESET = 'CREDIT_NOTE_MASTER_LIST_RESET'

//all creditnote with TAX 
export const CREDIT_NOTE_WITH_TAX_LIST_REQUEST = 'CREDIT_NOTE_WITH_TAX_LIST_REQUEST'
export const CREDIT_NOTE_WITH_TAX_LIST_SUCCESS = 'CREDIT_NOTE_WITH_TAX_LIST_SUCCESS'
export const CREDIT_NOTE_WITH_TAX_LIST_FAIL = 'CREDIT_NOTE_WITH_TAX_LIST_FAIL'
export const CREDIT_NOTE_WITH_TAX_LIST_RESET = 'CREDIT_NOTE_WITH_TAX_LIST_RESET'