//create
export const  SALES_ORDER_CREATE_REQUEST = ' SALES_ORDER_CREATE_REQUEST'
export const  SALES_ORDER_CREATE_SUCCESS = ' SALES_ORDER_CREATE_SUCCESS'
export const  SALES_ORDER_CREATE_FAIL = ' SALES_ORDER_CREATE_FAIL'
export const  SALES_ORDER_CREATE_RESET = ' SALES_ORDER_CREATE_RESET'

//read
export const SALES_ORDER_DETAILS_REQUEST = 'SALES_ORDER_DETAILS_REQUEST'
export const SALES_ORDER_DETAILS_SUCCESS = 'SALES_ORDER_DETAILS_SUCCESS'
export const SALES_ORDER_DETAILS_FAIL = 'SALES_ORDER_DETAILS_FAIL'
export const SALES_ORDER_DETAILS_RESET = 'SALES_ORDER_DETAILS_RESET'

//update
export const SALES_ORDER_UPDATE_REQUEST = 'SALES_ORDER_UPDATE_REQUEST'
export const SALES_ORDER_UPDATE_SUCCESS = 'SALES_ORDER_UPDATE_SUCCESS'
export const SALES_ORDER_UPDATE_FAIL = 'SALES_ORDER_UPDATE_FAIL'
export const SALES_ORDER_UPDATE_RESET = 'SALES_ORDER_UPDATE_RESET'

//delete
export const SALES_ORDER_DELETE_REQUEST = 'SALES_ORDER_DELETE_REQUEST'
export const SALES_ORDER_DELETE_SUCCESS = 'SALES_ORDER_DELETE_SUCCESS'
export const SALES_ORDER_DELETE_FAIL = 'SALES_ORDER_DELETE_FAIL'
export const SALES_ORDER_DELETE_RESET = 'SALES_ORDER_DELETE_RESET'

//all records
export const SALES_ORDER_LIST_REQUEST = 'SALES_ORDER_LIST_REQUEST'
export const SALES_ORDER_LIST_SUCCESS = 'SALES_ORDER_LIST_SUCCESS'
export const SALES_ORDER_LIST_FAIL = 'SALES_ORDER_LIST_FAIL'
export const SALES_ORDER_LIST_RESET = 'SALES_ORDER_LIST_RESET'

//all master data for JC Master
export const SALES_ORDER_MASTER_LIST_REQUEST = 'SALES_ORDER_MASTER_LIST_REQUEST'
export const SALES_ORDER_MASTER_LIST_SUCCESS = 'SALES_ORDER_MASTER_LIST_SUCCESS'
export const SALES_ORDER_MASTER_LIST_FAIL = 'SALES_ORDER_MASTER_LIST_FAIL'
export const SALES_ORDER_MASTER_LIST_RESET = 'SALES_ORDER_MASTER_LIST_RESET'

//getBackOrdersBySO
export const BACK_ORDER_LIST_REQUEST = 'BACK_ORDER_LIST_REQUEST'
export const BACK_ORDER_LIST_SUCCESS = 'BACK_ORDER_LIST_SUCCESS'
export const BACK_ORDER_LIST_FAIL = 'BACK_ORDER_LIST_FAIL'
export const BACK_ORDER_LIST_RESET = 'BACK_ORDER_LIST_RESET'

//getSODetailsByLine
export const SO_DETAILS_LIST_REQUEST = 'SO_DETAILS_LIST_REQUEST'
export const SO_DETAILS_LIST_SUCCESS = 'SO_DETAILS_LIST_SUCCESS'
export const SO_DETAILS_LIST_FAIL = 'SO_DETAILS_LIST_FAIL'
export const SO_DETAILS_LIST_RESET = 'SO_DETAILS_LIST_RESET'

//getCancelSODetailsByLine
export const CANCEL_SO_DETAILS_LIST_REQUEST = 'CANCEL_SO_DETAILS_LIST_REQUEST'
export const CANCEL_SO_DETAILS_LIST_SUCCESS = 'CANCEL_SO_DETAILS_LIST_SUCCESS'
export const CANCEL_SO_DETAILS_LIST_FAIL = 'CANCEL_SO_DETAILS_LIST_FAIL'
export const CANCEL_SO_DETAILS_LIST_RESET = 'CANCEL_SO_DETAILS_LIST_RESET'

//getbackorderbyjc
export const BACK_ORDER_BY_JC_LIST_REQUEST = 'BACK_ORDER_BY_JC_LIST_REQUEST'
export const BACK_ORDER_BY_JC_LIST_SUCCESS = 'BACK_ORDER_BY_JC_LIST_SUCCESS'
export const BACK_ORDER_BY_JC_LIST_FAIL = 'BACK_ORDER_BY_JC_LIST_FAIL'
export const BACK_ORDER_BY_JC_LIST_RESET = 'BACK_ORDER_BY_JC_LIST_RESET'

//getAllJCMastersForReports
export const SALES_ORDER_JC_MASTER_LIST_REQUEST = 'SALES_ORDER_JC_MASTER_LIST_REQUEST'
export const SALES_ORDER_JC_MASTER_LIST_SUCCESS = 'SALES_ORDER_JC_MASTER_LIST_SUCCESS'
export const SALES_ORDER_JC_MASTER_LIST_FAIL = 'SALES_ORDER_JC_MASTER_LIST_FAIL'
export const SALES_ORDER_JC_MASTER_LIST_RESET = 'SALES_ORDER_JC_MASTER_LIST_RESET'

//getCustomerOpenSalesOrders
export const OPEN_CUSTOMER_SO_LIST_REQUEST = 'OPEN_CUSTOMER_SO_LIST_REQUEST'
export const OPEN_CUSTOMER_SO_LIST_SUCCESS = 'OPEN_CUSTOMER_SO_LIST_SUCCESS'
export const OPEN_CUSTOMER_SO_LIST_FAIL = 'OPEN_CUSTOMER_SO_LIST_FAIL'
export const OPEN_CUSTOMER_SO_LIST_RESET = 'OPEN_CUSTOMER_SO_LIST_RESET'

//getBalancedQtyBySO
export const OPEN_SALES_ORDER_REQUEST = 'OPEN_SALES_ORDER_REQUEST'
export const OPEN_SALES_ORDER_SUCCESS = 'OPEN_SALES_ORDER_SUCCESS'
export const OPEN_SALES_ORDER_FAIL = 'OPEN_SALES_ORDER_FAIL'
export const OPEN_SALES_ORDER_RESET = 'OPEN_SALES_ORDER_RESET'

//updateCancelSOLineQty
export const CANCEL_SO_LINE_UPDATE_REQUEST = 'CANCEL_SO_LINE_UPDATE_REQUEST'
export const CANCEL_SO_LINE_UPDATE_SUCCESS = 'CANCEL_SO_LINE_UPDATE_SUCCESS'
export const CANCEL_SO_LINE_UPDATE_FAIL = 'CANCEL_SO_LINE_UPDATE_FAIL'
export const CANCEL_SO_LINE_UPDATE_RESET = 'CANCEL_SO_LINE_UPDATE_RESET'