//create
export const  SALES_INVOICE_CREATE_REQUEST = 'SALES_INVOICE_CREATE_REQUEST'
export const  SALES_INVOICE_CREATE_SUCCESS = 'SALES_INVOICE_CREATE_SUCCESS'
export const  SALES_INVOICE_CREATE_FAIL = 'SALES_INVOICE_CREATE_FAIL'
export const  SALES_INVOICE_CREATE_RESET = 'SALES_INVOICE_CREATE_RESET'

//read
export const SALES_INVOICE_DETAILS_REQUEST = 'SALES_INVOICE_DETAILS_REQUEST'
export const SALES_INVOICE_DETAILS_SUCCESS = 'SALES_INVOICE_DETAILS_SUCCESS'
export const SALES_INVOICE_DETAILS_FAIL = 'SALES_INVOICE_DETAILS_FAIL'
export const SALES_INVOICE_DETAILS_RESET = 'SALES_INVOICE_DETAILS_RESET'

//update
export const SALES_INVOICE_UPDATE_REQUEST = 'SALES_INVOICE_UPDATE_REQUEST'
export const SALES_INVOICE_UPDATE_SUCCESS = 'SALES_INVOICE_UPDATE_SUCCESS'
export const SALES_INVOICE_UPDATE_FAIL = 'SALES_INVOICE_UPDATE_FAIL'
export const SALES_INVOICE_UPDATE_RESET = 'SALES_INVOICE_UPDATE_RESET'

//delete
export const SALES_INVOICE_DELETE_REQUEST = 'SALES_INVOICE_DELETE_REQUEST'
export const SALES_INVOICE_DELETE_SUCCESS = 'SALES_INVOICE_DELETE_SUCCESS'
export const SALES_INVOICE_DELETE_FAIL = 'SALES_INVOICE_DELETE_FAIL'
export const SALES_INVOICE_DELETE_RESET = 'SALES_INVOICE_DELETE_RESET'

//all records
export const SALES_INVOICE_LIST_REQUEST = 'SALES_INVOICE_LIST_REQUEST'
export const SALES_INVOICE_LIST_SUCCESS = 'SALES_INVOICE_LIST_SUCCESS'
export const SALES_INVOICE_LIST_FAIL = 'SALES_INVOICE_LIST_FAIL'
export const SALES_INVOICE_LIST_RESET = 'SALES_INVOICE_LIST_RESET'

//all invoices with TAX 
export const SALES_INVOICE_WITH_TAX_LIST_REQUEST = 'SALES_INVOICE_WITH_TAX_LIST_REQUEST'
export const SALES_INVOICE_WITH_TAX_LIST_SUCCESS = 'SALES_INVOICE_WITH_TAX_LIST_SUCCESS'
export const SALES_INVOICE_WITH_TAX_LIST_FAIL = 'SALES_INVOICE_WITH_TAX_LIST_FAIL'
export const SALES_INVOICE_WITH_TAX_LIST_RESET = 'SALES_INVOICE_WITH_TAX_LIST_RESET'

//all master data for Sales Invoice
export const SALES_INVOICE_MASTER_LIST_REQUEST = 'SALES_INVOICE_MASTER_LIST_REQUEST'
export const SALES_INVOICE_MASTER_LIST_SUCCESS = 'SALES_INVOICE_MASTER_LIST_SUCCESS'
export const SALES_INVOICE_MASTER_LIST_FAIL = 'SALES_INVOICE_MASTER_LIST_FAIL'
export const SALES_INVOICE_MASTER_LIST_RESET = 'SALES_INVOICE_MASTER_LIST_RESET'

//all open SALES_INVOICE records
export const SALES_INVOICE_OPEN_LIST_REQUEST = 'SALES_INVOICE_OPEN_LIST_REQUEST'
export const SALES_INVOICE_OPEN_LIST_SUCCESS = 'SALES_INVOICE_OPEN_LIST_SUCCESS'
export const SALES_INVOICE_OPEN_LIST_FAIL = 'SALES_INVOICE_OPEN_LIST_FAIL'
export const SALES_INVOICE_OPEN_LIST_RESET = 'SALES_INVOICE_OPEN_LIST_RESET'

//all Approved SALES_INVOICE records
export const SALES_INVOICE_APPROVED_LIST_REQUEST = 'SALES_INVOICE_APPROVED_LIST_REQUEST'
export const SALES_INVOICE_APPROVED_LIST_SUCCESS = 'SALES_INVOICE_APPROVED_LIST_SUCCESS'
export const SALES_INVOICE_APPROVED_LIST_FAIL = 'SALES_INVOICE_APPROVED_LIST_FAIL'
export const SALES_INVOICE_APPROVED_LIST_RESET = 'SALES_INVOICE_APPROVED_LIST_RESET'

//all CUSTOMER SALES INVOICE records
export const CUSTOMER_SALES_INVOICE_LIST_REQUEST = 'CUSTOMER_SALES_INVOICE_LIST_REQUEST'
export const CUSTOMER_SALES_INVOICE_LIST_SUCCESS = 'CUSTOMER_SALES_INVOICE_LIST_SUCCESS'
export const CUSTOMER_SALES_INVOICE_LIST_FAIL = 'CUSTOMER_SALES_INVOICE_LIST_FAIL'
export const CUSTOMER_SALES_INVOICE_LIST_RESET = 'CUSTOMER_SALES_INVOICE_LIST_RESET'

//getSIDetailsByLine
export const SI_DETAILS_LIST_REQUEST = 'SI_DETAILS_LIST_REQUEST'
export const SI_DETAILS_LIST_SUCCESS = 'SI_DETAILS_LIST_SUCCESS'
export const SI_DETAILS_LIST_FAIL = 'SI_DETAILS_LIST_FAIL'
export const SI_DETAILS_LIST_RESET = 'SI_DETAILS_LIST_RESET'


//getSIDetailsByDispatch
export const SI_DISPATCH_DETAILS_LIST_REQUEST = 'SI_DISPATCH_DETAILS_LIST_REQUEST'
export const SI_DISPATCH_DETAILS_LIST_SUCCESS = 'SI_DISPATCH_DETAILS_LIST_SUCCESS'
export const SI_DISPATCH_DETAILS_LIST_FAIL = 'SI_DISPATCH_DETAILS_LIST_FAIL'
export const SI_DISPATCH_DETAILS_LIST_RESET = 'SI_DISPATCH_DETAILS_LIST_RESET'