//create
export const  APP_PARAMETER_CREATE_REQUEST = 'APP_PARAMETER_CREATE_REQUEST'
export const  APP_PARAMETER_CREATE_SUCCESS = 'APP_PARAMETER_CREATE_SUCCESS'
export const  APP_PARAMETER_CREATE_FAIL = 'APP_PARAMETER_CREATE_FAIL'
export const  APP_PARAMETER_CREATE_RESET = 'APP_PARAMETER_CREATE_RESET'

//read
export const APP_PARAMETER_DETAILS_REQUEST = 'APP_PARAMETER_DETAILS_REQUEST'
export const APP_PARAMETER_DETAILS_SUCCESS = 'APP_PARAMETER_DETAILS_SUCCESS'
export const APP_PARAMETER_DETAILS_FAIL = 'APP_PARAMETER_DETAILS_FAIL'
export const APP_PARAMETER_DETAILS_RESET = 'APP_PARAMETER_DETAILS_RESET'

//update
export const APP_PARAMETER_UPDATE_REQUEST = 'APP_PARAMETER_UPDATE_REQUEST'
export const APP_PARAMETER_UPDATE_SUCCESS = 'APP_PARAMETER_UPDATE_SUCCESS'
export const APP_PARAMETER_UPDATE_FAIL = 'APP_PARAMETER_UPDATE_FAIL'
export const APP_PARAMETER_UPDATE_RESET = 'APP_PARAMETER_UPDATE_RESET'

//delete
export const APP_PARAMETER_DELETE_REQUEST = 'APP_PARAMETER_DELETE_REQUEST'
export const APP_PARAMETER_DELETE_SUCCESS = 'APP_PARAMETER_DELETE_SUCCESS'
export const APP_PARAMETER_DELETE_FAIL = 'APP_PARAMETER_DELETE_FAIL'
export const APP_PARAMETER_DELETE_RESET = 'APP_PARAMETER_DELETE_RESET'

//all records
export const APP_PARAMETER_LIST_REQUEST = 'APP_PARAMETER_LIST_REQUEST'
export const APP_PARAMETER_LIST_SUCCESS = 'APP_PARAMETER_LIST_SUCCESS'
export const APP_PARAMETER_LIST_FAIL = 'APP_PARAMETER_LIST_FAIL'
export const APP_PARAMETER_LIST_RESET = 'APP_PARAMETER_LIST_RESET'

//all master data for Module
export const APP_PARAMETER_MASTER_LIST_REQUEST = 'APP_PARAMETER_MASTER_LIST_REQUEST'
export const APP_PARAMETER_MASTER_LIST_SUCCESS = 'APP_PARAMETER_MASTER_LIST_SUCCESS'
export const APP_PARAMETER_MASTER_LIST_FAIL = 'APP_PARAMETER_MASTER_LIST_FAIL'
export const APP_PARAMETER_MASTER_LIST_RESET = 'APP_PARAMETER_MASTER_LIST_RESET'