//create
export const  AUTO_INCREMENT_CREATE_REQUEST = 'AUTO_INCREMENT_CREATE_REQUEST'
export const  AUTO_INCREMENT_CREATE_SUCCESS = 'AUTO_INCREMENT_CREATE_SUCCESS'
export const  AUTO_INCREMENT_CREATE_FAIL = 'AUTO_INCREMENT_CREATE_FAIL'
export const  AUTO_INCREMENT_CREATE_RESET = 'AUTO_INCREMENT_CREATE_RESET'

//read
export const AUTO_INCREMENT_DETAILS_REQUEST = 'AUTO_INCREMENT_DETAILS_REQUEST'
export const AUTO_INCREMENT_DETAILS_SUCCESS = 'AUTO_INCREMENT_DETAILS_SUCCESS'
export const AUTO_INCREMENT_DETAILS_FAIL = 'AUTO_INCREMENT_DETAILS_FAIL'
export const AUTO_INCREMENT_DETAILS_RESET = 'AUTO_INCREMENT_DETAILS_RESET'

//update
export const AUTO_INCREMENT_UPDATE_REQUEST = 'AUTO_INCREMENT_UPDATE_REQUEST'
export const AUTO_INCREMENT_UPDATE_SUCCESS = 'AUTO_INCREMENT_UPDATE_SUCCESS'
export const AUTO_INCREMENT_UPDATE_FAIL = 'AUTO_INCREMENT_UPDATE_FAIL'
export const AUTO_INCREMENT_UPDATE_RESET = 'AUTO_INCREMENT_UPDATE_RESET'

//delete
export const AUTO_INCREMENT_DELETE_REQUEST = 'AUTO_INCREMENT_DELETE_REQUEST'
export const AUTO_INCREMENT_DELETE_SUCCESS = 'AUTO_INCREMENT_DELETE_SUCCESS'
export const AUTO_INCREMENT_DELETE_FAIL = 'AUTO_INCREMENT_DELETE_FAIL'
export const AUTO_INCREMENT_DELETE_RESET = 'AUTO_INCREMENT_DELETE_RESET'

//all records
export const AUTO_INCREMENT_LIST_REQUEST = 'AUTO_INCREMENT_LIST_REQUEST'
export const AUTO_INCREMENT_LIST_SUCCESS = 'AUTO_INCREMENT_LIST_SUCCESS'
export const AUTO_INCREMENT_LIST_FAIL = 'AUTO_INCREMENT_LIST_FAIL'
export const AUTO_INCREMENT_LIST_RESET = 'AUTO_INCREMENT_LIST_RESET'

//all master data for Module
export const AUTO_INCREMENT_MASTER_LIST_REQUEST = 'AUTO_INCREMENT_MASTER_LIST_REQUEST'
export const AUTO_INCREMENT_MASTER_LIST_SUCCESS = 'AUTO_INCREMENT_MASTER_LIST_SUCCESS'
export const AUTO_INCREMENT_MASTER_LIST_FAIL = 'AUTO_INCREMENT_MASTER_LIST_FAIL'
export const AUTO_INCREMENT_MASTER_LIST_RESET = 'AUTO_INCREMENT_MASTER_LIST_RESET'