//create
export const  HSN_CREATE_REQUEST = ' HSN_CREATE_REQUEST'
export const  HSN_CREATE_SUCCESS = ' HSN_CREATE_SUCCESS'
export const  HSN_CREATE_FAIL = ' HSN_CREATE_FAIL'
export const  HSN_CREATE_RESET = ' HSN_CREATE_RESET'

//read
export const HSN_DETAILS_REQUEST = 'HSN_DETAILS_REQUEST'
export const HSN_DETAILS_SUCCESS = 'HSN_DETAILS_SUCCESS'
export const HSN_DETAILS_FAIL = 'HSN_DETAILS_FAIL'
export const HSN_DETAILS_RESET = 'HSN_DETAILS_RESET'

//update
export const HSN_UPDATE_REQUEST = 'HSN_UPDATE_REQUEST'
export const HSN_UPDATE_SUCCESS = 'HSN_UPDATE_SUCCESS'
export const HSN_UPDATE_FAIL = 'HSN_UPDATE_FAIL'
export const HSN_UPDATE_RESET = 'HSN_UPDATE_RESET'

//delete
export const HSN_DELETE_REQUEST = 'HSN_DELETE_REQUEST'
export const HSN_DELETE_SUCCESS = 'HSN_DELETE_SUCCESS'
export const HSN_DELETE_FAIL = 'HSN_DELETE_FAIL'
export const HSN_DELETE_RESET = 'HSN_DELETE_RESET'

//all records
export const HSN_LIST_REQUEST = 'HSN_LIST_REQUEST'
export const HSN_LIST_SUCCESS = 'HSN_LIST_SUCCESS'
export const HSN_LIST_FAIL = 'HSN_LIST_FAIL'
export const HSN_LIST_RESET = 'HSN_LIST_RESET'

//all master data for Job Card Screen
export const HSN_MASTER_LIST_REQUEST = 'HSN_MASTER_LIST_REQUEST'
export const HSN_MASTER_LIST_SUCCESS = 'HSN_MASTER_LIST_SUCCESS'
export const HSN_MASTER_LIST_FAIL = 'HSN_MASTER_LIST_FAIL'
export const HSN_MASTER_LIST_RESET = 'HSN_MASTER_LIST_RESET'