//create
export const  ISSUE_CREATE_REQUEST = ' ISSUE_CREATE_REQUEST'
export const  ISSUE_CREATE_SUCCESS = ' ISSUE_CREATE_SUCCESS'
export const  ISSUE_CREATE_FAIL = ' ISSUE_CREATE_FAIL'
export const  ISSUE_CREATE_RESET = ' ISSUE_CREATE_RESET'

//read
export const ISSUE_DETAILS_REQUEST = 'ISSUE_DETAILS_REQUEST'
export const ISSUE_DETAILS_SUCCESS = 'ISSUE_DETAILS_SUCCESS'
export const ISSUE_DETAILS_FAIL = 'ISSUE_DETAILS_FAIL'
export const ISSUE_DETAILS_RESET = 'ISSUE_DETAILS_RESET'

//update
export const ISSUE_UPDATE_REQUEST = 'ISSUE_UPDATE_REQUEST'
export const ISSUE_UPDATE_SUCCESS = 'ISSUE_UPDATE_SUCCESS'
export const ISSUE_UPDATE_FAIL = 'ISSUE_UPDATE_FAIL'
export const ISSUE_UPDATE_RESET = 'ISSUE_UPDATE_RESET'

//delete
export const ISSUE_DELETE_REQUEST = 'ISSUE_DELETE_REQUEST'
export const ISSUE_DELETE_SUCCESS = 'ISSUE_DELETE_SUCCESS'
export const ISSUE_DELETE_FAIL = 'ISSUE_DELETE_FAIL'
export const ISSUE_DELETE_RESET = 'ISSUE_DELETE_RESET'

//all records
export const ISSUE_LIST_REQUEST = 'ISSUE_LIST_REQUEST'
export const ISSUE_LIST_SUCCESS = 'ISSUE_LIST_SUCCESS'
export const ISSUE_LIST_FAIL = 'ISSUE_LIST_FAIL'
export const ISSUE_LIST_RESET = 'ISSUE_LIST_RESET'

//all master data for Module
export const ISSUE_MASTER_LIST_REQUEST = 'ISSUE_MASTER_LIST_REQUEST'
export const ISSUE_MASTER_LIST_SUCCESS = 'ISSUE_MASTER_LIST_SUCCESS'
export const ISSUE_MASTER_LIST_FAIL = 'ISSUE_MASTER_LIST_FAIL'
export const ISSUE_MASTER_LIST_RESET = 'ISSUE_MASTER_LIST_RESET'