//create
export const  JC_CREATE_REQUEST = ' JC_CREATE_REQUEST'
export const  JC_CREATE_SUCCESS = ' JC_CREATE_SUCCESS'
export const  JC_CREATE_FAIL = ' JC_CREATE_FAIL'
export const  JC_CREATE_RESET = ' JC_CREATE_RESET'

//read
export const JC_DETAILS_REQUEST = 'JC_DETAILS_REQUEST'
export const JC_DETAILS_SUCCESS = 'JC_DETAILS_SUCCESS'
export const JC_DETAILS_FAIL = 'JC_DETAILS_FAIL'
export const JC_DETAILS_RESET = 'JC_DETAILS_RESET'

//update
export const JC_UPDATE_REQUEST = 'JC_UPDATE_REQUEST'
export const JC_UPDATE_SUCCESS = 'JC_UPDATE_SUCCESS'
export const JC_UPDATE_FAIL = 'JC_UPDATE_FAIL'
export const JC_UPDATE_RESET = 'JC_UPDATE_RESET'

//delete
export const JC_DELETE_REQUEST = 'JC_DELETE_REQUEST'
export const JC_DELETE_SUCCESS = 'JC_DELETE_SUCCESS'
export const JC_DELETE_FAIL = 'JC_DELETE_FAIL'
export const JC_DELETE_RESET = 'JC_DELETE_RESET'

//all records
export const JC_LIST_REQUEST = 'JC_LIST_REQUEST'
export const JC_LIST_SUCCESS = 'JC_LIST_SUCCESS'
export const JC_LIST_FAIL = 'JC_LIST_FAIL'
export const JC_LIST_RESET = 'JC_LIST_RESET'

//all JC records
export const JC_ALL_LIST_REQUEST = 'JC_ALL_LIST_REQUEST'
export const JC_ALL_LIST_SUCCESS = 'JC_ALL_LIST_SUCCESS'
export const JC_ALL_LIST_FAIL = 'JC_ALL_LIST_FAIL'
export const JC_ALL_LIST_RESET = 'JC_ALL_LIST_RESET'


//all master data for JC Master
export const JC_MASTER_LIST_REQUEST = 'JC_MASTER_LIST_REQUEST'
export const JC_MASTER_LIST_SUCCESS = 'JC_MASTER_LIST_SUCCESS'
export const JC_MASTER_LIST_FAIL = 'JC_MASTER_LIST_FAIL'
export const JC_MASTER_LIST_RESET = 'JC_MASTER_LIST_RESET'

//all Customer specific JC Master Data
export const JC_MASTER_CUSTOMER_LIST_REQUEST = 'JC_MASTER_CUSTOMER_LIST_REQUEST'
export const JC_MASTER_CUSTOMER_LIST_SUCCESS = 'JC_MASTER_CUSTOMER_LIST_SUCCESS'
export const JC_MASTER_CUSTOMER_LIST_FAIL = 'JC_MASTER_CUSTOMER_LIST_FAIL'
export const JC_MASTER_CUSTOMER_LIST_RESET = 'JC_MASTER_CUSTOMER_LIST_RESET'

//JC Master Report
export const JC_MASTER_REPORT_REQUEST = 'JC_MASTER_REPORT_REQUEST'
export const JC_MASTER_REPORT_SUCCESS = 'JC_MASTER_REPORT_SUCCESS'
export const JC_MASTER_REPORT_FAIL = 'JC_MASTER_REPORT_FAIL'
export const JC_MASTER_REPORT_RESET = 'JC_MASTER_REPORT_RESET'


//all Customer specific JC POs Master Data
export const JC_MASTER_CUSTOMER_PO_LIST_REQUEST = 'JC_MASTER_CUSTOMER_PO_LIST_REQUEST'
export const JC_MASTER_CUSTOMER_PO_LIST_SUCCESS = 'JC_MASTER_CUSTOMER_PO_LIST_SUCCESS'
export const JC_MASTER_CUSTOMER_PO_LIST_FAIL = 'JC_MASTER_CUSTOMER_PO_LIST_FAIL'
export const JC_MASTER_CUSTOMER_PO_LIST_RESET = 'JC_MASTER_CUSTOMER_PO_LIST_RESET'