//create
export const  MACHINE_MASTER_CREATE_REQUEST = ' MACHINE_MASTER_CREATE_REQUEST'
export const  MACHINE_MASTER_CREATE_SUCCESS = ' MACHINE_MASTER_CREATE_SUCCESS'
export const  MACHINE_MASTER_CREATE_FAIL = ' MACHINE_MASTER_CREATE_FAIL'
export const  MACHINE_MASTER_CREATE_RESET = ' MACHINE_MASTER_CREATE_RESET'

//read
export const MACHINE_MASTER_DETAILS_REQUEST = 'MACHINE_MASTER_DETAILS_REQUEST'
export const MACHINE_MASTER_DETAILS_SUCCESS = 'MACHINE_MASTER_DETAILS_SUCCESS'
export const MACHINE_MASTER_DETAILS_FAIL = 'MACHINE_MASTER_DETAILS_FAIL'
export const MACHINE_MASTER_DETAILS_RESET = 'MACHINE_MASTER_DETAILS_RESET'

//update
export const MACHINE_MASTER_UPDATE_REQUEST = 'MACHINE_MASTER_UPDATE_REQUEST'
export const MACHINE_MASTER_UPDATE_SUCCESS = 'MACHINE_MASTER_UPDATE_SUCCESS'
export const MACHINE_MASTER_UPDATE_FAIL = 'MACHINE_MASTER_UPDATE_FAIL'
export const MACHINE_MASTER_UPDATE_RESET = 'MACHINE_MASTER_UPDATE_RESET'

//delete
export const MACHINE_MASTER_DELETE_REQUEST = 'MACHINE_MASTER_DELETE_REQUEST'
export const MACHINE_MASTER_DELETE_SUCCESS = 'MACHINE_MASTER_DELETE_SUCCESS'
export const MACHINE_MASTER_DELETE_FAIL = 'MACHINE_MASTER_DELETE_FAIL'
export const MACHINE_MASTER_DELETE_RESET = 'MACHINE_MASTER_DELETE_RESET'

//all records
export const MACHINE_MASTER_LIST_REQUEST = 'MACHINE_MASTER_LIST_REQUEST'
export const MACHINE_MASTER_LIST_SUCCESS = 'MACHINE_MASTER_LIST_SUCCESS'
export const MACHINE_MASTER_LIST_FAIL = 'MACHINE_MASTER_LIST_FAIL'
export const MACHINE_MASTER_LIST_RESET = 'MACHINE_MASTER_LIST_RESET'

//all master data for Job Card Screen
export const MACHINE_MASTER_MASTER_LIST_REQUEST = 'MACHINE_MASTER_MASTER_LIST_REQUEST'
export const MACHINE_MASTER_MASTER_LIST_SUCCESS = 'MACHINE_MASTER_MASTER_LIST_SUCCESS'
export const MACHINE_MASTER_MASTER_LIST_FAIL = 'MACHINE_MASTER_MASTER_LIST_FAIL'
export const MACHINE_MASTER_MASTER_LIST_RESET = 'MACHINE_MASTER_MASTER_LIST_RESET'