//create
export const  SAC_CREATE_REQUEST = ' SAC_CREATE_REQUEST'
export const  SAC_CREATE_SUCCESS = ' SAC_CREATE_SUCCESS'
export const  SAC_CREATE_FAIL = ' SAC_CREATE_FAIL'
export const  SAC_CREATE_RESET = ' SAC_CREATE_RESET'

//read
export const SAC_DETAILS_REQUEST = 'SAC_DETAILS_REQUEST'
export const SAC_DETAILS_SUCCESS = 'SAC_DETAILS_SUCCESS'
export const SAC_DETAILS_FAIL = 'SAC_DETAILS_FAIL'
export const SAC_DETAILS_RESET = 'SAC_DETAILS_RESET'

//update
export const SAC_UPDATE_REQUEST = 'SAC_UPDATE_REQUEST'
export const SAC_UPDATE_SUCCESS = 'SAC_UPDATE_SUCCESS'
export const SAC_UPDATE_FAIL = 'SAC_UPDATE_FAIL'
export const SAC_UPDATE_RESET = 'SAC_UPDATE_RESET'

//delete
export const SAC_DELETE_REQUEST = 'SAC_DELETE_REQUEST'
export const SAC_DELETE_SUCCESS = 'SAC_DELETE_SUCCESS'
export const SAC_DELETE_FAIL = 'SAC_DELETE_FAIL'
export const SAC_DELETE_RESET = 'SAC_DELETE_RESET'

//all records
export const SAC_LIST_REQUEST = 'SAC_LIST_REQUEST'
export const SAC_LIST_SUCCESS = 'SAC_LIST_SUCCESS'
export const SAC_LIST_FAIL = 'SAC_LIST_FAIL'
export const SAC_LIST_RESET = 'SAC_LIST_RESET'

//all master data for Job Card Screen
export const SAC_MASTER_LIST_REQUEST = 'SAC_MASTER_LIST_REQUEST'
export const SAC_MASTER_LIST_SUCCESS = 'SAC_MASTER_LIST_SUCCESS'
export const SAC_MASTER_LIST_FAIL = 'SAC_MASTER_LIST_FAIL'
export const SAC_MASTER_LIST_RESET = 'SAC_MASTER_LIST_RESET'