//create
export const  SERVICE_MASTER_CREATE_REQUEST = 'SERVICE_MASTER_CREATE_REQUEST'
export const  SERVICE_MASTER_CREATE_SUCCESS = 'SERVICE_MASTER_CREATE_SUCCESS'
export const  SERVICE_MASTER_CREATE_FAIL = 'SERVICE_MASTER_CREATE_FAIL'
export const  SERVICE_MASTER_CREATE_RESET = 'SERVICE_MASTER_CREATE_RESET'

//read
export const SERVICE_MASTER_DETAILS_REQUEST = 'SERVICE_MASTER_DETAILS_REQUEST'
export const SERVICE_MASTER_DETAILS_SUCCESS = 'SERVICE_MASTER_DETAILS_SUCCESS'
export const SERVICE_MASTER_DETAILS_FAIL = 'SERVICE_MASTER_DETAILS_FAIL'
export const SERVICE_MASTER_DETAILS_RESET = 'SERVICE_MASTER_DETAILS_RESET'

//update
export const SERVICE_MASTER_UPDATE_REQUEST = 'SERVICE_MASTER_UPDATE_REQUEST'
export const SERVICE_MASTER_UPDATE_SUCCESS = 'SERVICE_MASTER_UPDATE_SUCCESS'
export const SERVICE_MASTER_UPDATE_FAIL = 'SERVICE_MASTER_UPDATE_FAIL'
export const SERVICE_MASTER_UPDATE_RESET = 'SERVICE_MASTER_UPDATE_RESET'

//delete
export const SERVICE_MASTER_DELETE_REQUEST = 'SERVICE_MASTER_DELETE_REQUEST'
export const SERVICE_MASTER_DELETE_SUCCESS = 'SERVICE_MASTER_DELETE_SUCCESS'
export const SERVICE_MASTER_DELETE_FAIL = 'SERVICE_MASTER_DELETE_FAIL'
export const SERVICE_MASTER_DELETE_RESET = 'SERVICE_MASTER_DELETE_RESET'

//all records
export const SERVICE_MASTER_LIST_REQUEST = 'SERVICE_MASTER_LIST_REQUEST'
export const SERVICE_MASTER_LIST_SUCCESS = 'SERVICE_MASTER_LIST_SUCCESS'
export const SERVICE_MASTER_LIST_FAIL = 'SERVICE_MASTER_LIST_FAIL'
export const SERVICE_MASTER_LIST_RESET = 'SERVICE_MASTER_LIST_RESET'

//all master data for Module
export const SERVICE_MASTER_MASTER_LIST_REQUEST = 'SERVICE_MASTER_MASTER_LIST_REQUEST'
export const SERVICE_MASTER_MASTER_LIST_SUCCESS = 'SERVICE_MASTER_MASTER_LIST_SUCCESS'
export const SERVICE_MASTER_MASTER_LIST_FAIL = 'SERVICE_MASTER_MASTER_LIST_FAIL'
export const SERVICE_MASTER_MASTER_LIST_RESET = 'SERVICE_MASTER_MASTER_LIST_RESET'