//create
export const  SERVICE_CODE_CREATE_REQUEST = 'SERVICE_CODE_CREATE_REQUEST'
export const  SERVICE_CODE_CREATE_SUCCESS = 'SERVICE_CODE_CREATE_SUCCESS'
export const  SERVICE_CODE_CREATE_FAIL = 'SERVICE_CODE_CREATE_FAIL'
export const  SERVICE_CODE_CREATE_RESET = 'SERVICE_CODE_CREATE_RESET'

//read
export const SERVICE_CODE_DETAILS_REQUEST = 'SERVICE_CODE_DETAILS_REQUEST'
export const SERVICE_CODE_DETAILS_SUCCESS = 'SERVICE_CODE_DETAILS_SUCCESS'
export const SERVICE_CODE_DETAILS_FAIL = 'SERVICE_CODE_DETAILS_FAIL'
export const SERVICE_CODE_DETAILS_RESET = 'SERVICE_CODE_DETAILS_RESET'

//update
export const SERVICE_CODE_UPDATE_REQUEST = 'SERVICE_CODE_UPDATE_REQUEST'
export const SERVICE_CODE_UPDATE_SUCCESS = 'SERVICE_CODE_UPDATE_SUCCESS'
export const SERVICE_CODE_UPDATE_FAIL = 'SERVICE_CODE_UPDATE_FAIL'
export const SERVICE_CODE_UPDATE_RESET = 'SERVICE_CODE_UPDATE_RESET'

//delete
export const SERVICE_CODE_DELETE_REQUEST = 'SERVICE_CODE_DELETE_REQUEST'
export const SERVICE_CODE_DELETE_SUCCESS = 'SERVICE_CODE_DELETE_SUCCESS'
export const SERVICE_CODE_DELETE_FAIL = 'SERVICE_CODE_DELETE_FAIL'
export const SERVICE_CODE_DELETE_RESET = 'SERVICE_CODE_DELETE_RESET'

//all records
export const SERVICE_CODE_LIST_REQUEST = 'SERVICE_CODE_LIST_REQUEST'
export const SERVICE_CODE_LIST_SUCCESS = 'SERVICE_CODE_LIST_SUCCESS'
export const SERVICE_CODE_LIST_FAIL = 'SERVICE_CODE_LIST_FAIL'
export const SERVICE_CODE_LIST_RESET = 'SERVICE_CODE_LIST_RESET'


//all master data for Service Code Master
export const SERVICE_CODE_MASTER_DATA_REQUEST = 'SERVICE_CODE_MASTER_DATA_REQUEST'
export const SERVICE_CODE_MASTER_DATA_SUCCESS = 'SERVICE_CODE_MASTER_DATA_SUCCESS'
export const SERVICE_CODE_MASTER_DATA_FAIL = 'SERVICE_CODE_MASTER_DATA_FAIL'
export const SERVICE_CODE_MASTER_DATA_RESET = 'SERVICE_CODE_MASTER_DATA_RESET'