//create
export const  UOM_CREATE_REQUEST = 'UOM_CREATE_REQUEST'
export const  UOM_CREATE_SUCCESS = 'UOM_CREATE_SUCCESS'
export const  UOM_CREATE_FAIL = 'UOM_CREATE_FAIL'
export const  UOM_CREATE_RESET = 'UOM_CREATE_RESET'

//read
export const UOM_DETAILS_REQUEST = 'UOM_DETAILS_REQUEST'
export const UOM_DETAILS_SUCCESS = 'UOM_DETAILS_SUCCESS'
export const UOM_DETAILS_FAIL = 'UOM_DETAILS_FAIL'
export const UOM_DETAILS_RESET = 'UOM_DETAILS_RESET'

//update
export const UOM_UPDATE_REQUEST = 'UOM_UPDATE_REQUEST'
export const UOM_UPDATE_SUCCESS = 'UOM_UPDATE_SUCCESS'
export const UOM_UPDATE_FAIL = 'UOM_UPDATE_FAIL'
export const UOM_UPDATE_RESET = 'UOM_UPDATE_RESET'

//delete
export const UOM_DELETE_REQUEST = 'UOM_DELETE_REQUEST'
export const UOM_DELETE_SUCCESS = 'UOM_DELETE_SUCCESS'
export const UOM_DELETE_FAIL = 'UOM_DELETE_FAIL'
export const UOM_DELETE_RESET = 'UOM_DELETE_RESET'

//all records
export const UOM_LIST_REQUEST = 'UOM_LIST_REQUEST'
export const UOM_LIST_SUCCESS = 'UOM_LIST_SUCCESS'
export const UOM_LIST_FAIL = 'UOM_LIST_FAIL'
export const UOM_LIST_RESET = 'UOM_LIST_RESET'