export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_RESET = 'USER_LIST_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USER_MASTER_DATA_REQUEST = 'USER_MASTER_DATA_REQUEST'
export const USER_MASTER_DATA_SUCCESS = 'USER_MASTER_DATA_SUCCESS'
export const USER_MASTER_DATA_FAIL = 'USER_MASTER_DATA_FAIL'
export const USER_MASTER_DATA_RESET = 'USER_MASTER_DATA_RESET'

/** ROLE MANEGEMENT CONSTANTS */
//create
export const  ROLE_CREATE_REQUEST = ' ROLE_CREATE_REQUEST'
export const  ROLE_CREATE_SUCCESS = ' ROLE_CREATE_SUCCESS'
export const  ROLE_CREATE_FAIL = ' ROLE_CREATE_FAIL'
export const  ROLE_CREATE_RESET = ' ROLE_CREATE_RESET'

//read
export const ROLE_DETAILS_REQUEST = 'ROLE_DETAILS_REQUEST'
export const ROLE_DETAILS_SUCCESS = 'ROLE_DETAILS_SUCCESS'
export const ROLE_DETAILS_FAIL = 'ROLE_DETAILS_FAIL'
export const ROLE_DETAILS_RESET = 'ROLE_DETAILS_RESET'

//update
export const ROLE_UPDATE_REQUEST = 'ROLE_UPDATE_REQUEST'
export const ROLE_UPDATE_SUCCESS = 'ROLE_UPDATE_SUCCESS'
export const ROLE_UPDATE_FAIL = 'ROLE_UPDATE_FAIL'
export const ROLE_UPDATE_RESET = 'ROLE_UPDATE_RESET'

//delete
export const ROLE_DELETE_REQUEST = 'ROLE_DELETE_REQUEST'
export const ROLE_DELETE_SUCCESS = 'ROLE_DELETE_SUCCESS'
export const ROLE_DELETE_FAIL = 'ROLE_DELETE_FAIL'
export const ROLE_DELETE_RESET = 'ROLE_DELETE_RESET'

//all records
export const ROLE_LIST_REQUEST = 'ROLE_LIST_REQUEST'
export const ROLE_LIST_SUCCESS = 'ROLE_LIST_SUCCESS'
export const ROLE_LIST_FAIL = 'ROLE_LIST_FAIL'
export const ROLE_LIST_RESET = 'ROLE_LIST_RESET'

/** MENU MANAGEMENT */
//create
export const  MENU_CREATE_REQUEST = ' MENU_CREATE_REQUEST'
export const  MENU_CREATE_SUCCESS = ' MENU_CREATE_SUCCESS'
export const  MENU_CREATE_FAIL = ' MENU_CREATE_FAIL'
export const  MENU_CREATE_RESET = ' MENU_CREATE_RESET'

//read
export const MENU_DETAILS_REQUEST = 'MENU_DETAILS_REQUEST'
export const MENU_DETAILS_SUCCESS = 'MENU_DETAILS_SUCCESS'
export const MENU_DETAILS_FAIL = 'MENU_DETAILS_FAIL'
export const MENU_DETAILS_RESET = 'MENU_DETAILS_RESET'

//update
export const MENU_UPDATE_REQUEST = 'MENU_UPDATE_REQUEST'
export const MENU_UPDATE_SUCCESS = 'MENU_UPDATE_SUCCESS'
export const MENU_UPDATE_FAIL = 'MENU_UPDATE_FAIL'
export const MENU_UPDATE_RESET = 'MENU_UPDATE_RESET'

//delete
export const MENU_DELETE_REQUEST = 'MENU_DELETE_REQUEST'
export const MENU_DELETE_SUCCESS = 'MENU_DELETE_SUCCESS'
export const MENU_DELETE_FAIL = 'MENU_DELETE_FAIL'
export const MENU_DELETE_RESET = 'MENU_DELETE_RESET'

//all records
export const MENU_LIST_REQUEST = 'MENU_LIST_REQUEST'
export const MENU_LIST_SUCCESS = 'MENU_LIST_SUCCESS'
export const MENU_LIST_FAIL = 'MENU_LIST_FAIL'
export const MENU_LIST_RESET = 'MENU_LIST_RESET'

//sub menu records
export const SUBMENU_LIST_REQUEST = 'SUBMENU_LIST_REQUEST'
export const SUBMENU_LIST_SUCCESS = 'SUBMENU_LIST_SUCCESS'
export const SUBMENU_LIST_FAIL = 'SUBMENU_LIST_FAIL'
export const SUBMENU_LIST_RESET = 'SUBMENU_LIST_RESET'

//master data
export const MENU_MASTER_DATA_REQUEST = 'MENU_MASTER_DATA_REQUEST'
export const MENU_MASTER_DATA_SUCCESS = 'MENU_MASTER_DATA_SUCCESS'
export const MENU_MASTER_DATA_FAIL = 'MENU_MASTER_DATA_FAIL'
export const MENU_MASTER_DATA_RESET = 'MENU_MASTER_DATA_RESET'