//read
export const DASHBOARD_DETAILS_REQUEST = 'DASHBOARD_DETAILS_REQUEST'
export const DASHBOARD_DETAILS_SUCCESS = 'DASHBOARD_DETAILS_SUCCESS'
export const DASHBOARD_DETAILS_FAIL = 'DASHBOARD_DETAILS_FAIL'
export const DASHBOARD_DETAILS_RESET = 'DASHBOARD_DETAILS_RESET'

//chart read
export const DASHBOARD_CHART_REQUEST = 'DASHBOARD_CHART_REQUEST'
export const DASHBOARD_CHART_SUCCESS = 'DASHBOARD_CHART_SUCCESS'
export const DASHBOARD_CHART_FAIL = 'DASHBOARD_CHART_FAIL'
export const DASHBOARD_CHART_RESET = 'DASHBOARD_CHART_RESET'

//chart read
export const PRODUCTION_CHART_REQUEST = 'PRODUCTION_CHART_REQUEST'
export const PRODUCTION_CHART_SUCCESS = 'PRODUCTION_CHART_SUCCESS'
export const PRODUCTION_CHART_FAIL = 'PRODUCTION_CHART_FAIL'
export const PRODUCTION_CHART_RESET = 'PRODUCTION_CHART_RESET'

//sales dashboard
export const SALES_DASHBOARD_REQUEST = 'SALES_DASHBOARD_REQUEST'
export const SALES_DASHBOARD_SUCCESS = 'SALES_DASHBOARD_SUCCESS'
export const SALES_DASHBOARD_FAIL = 'SALES_DASHBOARD_FAIL'
export const SALES_DASHBOARD_RESET = 'SALES_DASHBOARD_RESET'

//qa dashboard
export const QA_DASHBOARD_REQUEST = 'QA_DASHBOARD_REQUEST'
export const QA_DASHBOARD_SUCCESS = 'QA_DASHBOARD_SUCCESS'
export const QA_DASHBOARD_FAIL = 'QA_DASHBOARD_FAIL'
export const QA_DASHBOARD_RESET = 'QA_DASHBOARD_RESET'

//ppm dashboard
export const PPM_DASHBOARD_REQUEST = 'PPM_DASHBOARD_REQUEST'
export const PPM_DASHBOARD_SUCCESS = 'PPM_DASHBOARD_SUCCESS'
export const PPM_DASHBOARD_FAIL = 'PPM_DASHBOARD_FAIL'
export const PPM_DASHBOARD_RESET = 'PPM_DASHBOARD_RESET'